# Generated by Django 2.1.1 on 2018-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title_id', models.CharField(max_length=100)),
                ('normalized_title', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=50000)),
                ('score', models.IntegerField(default=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
